version: '3'

services:
  ledger:
    build:
      context: ledger
    ports:
      - 5555:80
    volumes:
      - ./ledger:/app
  api:
    build:
      context: api
    ports:
      - 6666:80
    volumes:
      - ./api:/app
