version: '3'

services:
  ledger:
    build:
      context: ledger
    ports:
      - 80
    volumes:
      - ./ledger:/app
  api:
    build:
      context: api
    ports:
      - 80
    volumes:
      - ./api:/app
