version: '3'

services:
  ledger:
    build:
      context: ledger
    ports:
      - 5555:80
    volumes:
      - ./ledger:/app
    environment:
      - HTTP_LEDGER=ledger:80
  karma:
    build:
      context: karma
    ports:
      - 6666:80
    volumes:
      - ./karma:/app
